### PR TITLE
Complete all keywords and builtins

### PR DESCRIPTION
**Pull request by EmilyGraceSeville7cf**
image

### CODE REVIEW

**Comment by bmalehorn** [comment]
Hey @EmilyGraceSeville7cf , thanks for the PR!

I checked out your branch and it looks like the problem is you're registering it for the `plaintext` language, not `fish`. With the following change I could get suggestions working in vscode:

image

```diff
diff --git a/src/extension.ts b/src/extension.ts
index 0e8129f..3aeea40 100644
--- a/src/extension.ts
+++ b/src/extension.ts
@@ -62,7 +62,7 @@ export const activate = async (context: ExtensionContext): Promise<any> => {
   );
 
   context.subscriptions.push(
-    vscode.languages.registerCompletionItemProvider("plaintext", {
+    vscode.languages.registerCompletionItemProvider("fish", {
       provideCompletionItems(
         document: vscode.TextDocument,
         position: vscode.Position,
@@ -73,6 +73,8 @@ export const activate = async (context: ExtensionContext): Promise<any> => {
           new vscode.CompletionItem("if", vscode.CompletionItemKind.Keyword),
           new vscode.CompletionItem("while", vscode.CompletionItemKind.Keyword),
           new vscode.CompletionItem("for", vscode.CompletionItemKind.Keyword),
+          new vscode.CompletionItem("bmalehorn_was_here", vscode.CompletionItemKind.Keyword),
+
         ];
       },
     }),

```

**Comment by EmilyGraceSeville7cf** [comment]
@bmalehorn, now completion for all keywords and builtins is done.

**Comment by EmilyGraceSeville7cf** [comment]
I will add documentation for all commands.

**Comment by EmilyGraceSeville7cf** [comment]
> For the arguments with options, did you write it by hand?

Yeah. :)

**Pull request merged**
